
@baseUri = http://localhost:8182/api

### Index
GET {{baseUri}}/products HTTP/1.1
content-type: application/json

### Store
POST {{baseUri}}/products HTTP/1.1
content-type: application/json

{
    "name": "Produto criado via API/REST",
    "description": "Descrição do produto criado via API",
    "price": 29.90,
    "stock": 50
}

### Show
# 1 é o ID do produto neste exemplo
# Utilize um ID existente em sua base de dados.

GET {{baseUri}}/products/1 HTTP/1.1
Content-Type: application/json

### Update
# 1 é o ID do produto neste exemplo
# Utilize um ID existente em sua base de dados.

PUT {{baseUri}}/products/1 HTTP/1.1
Content-Type: application/json

{
    "name": "Produto ATUALIZADO via API/REST",
    "description": "Descrição atualizada via API",
    "price": 39.90,
    "stock": 30
}

### Delete
# 1 é o ID do produto neste exemplo.
# Utilize um ID existente em sua base de dados.
#
# Após a execução deste processo, o mesmo ID não funcionará
# em outras operações, pois o registro foi removido.

DELETE {{baseUri}}/products/1 HTTP/1.1
content-type: application/json

